### ISSUE TITLE
Installer scripts do not handle table prefixes

### ISSUE THREAD

**Issue by knoxjamesus** [trustpilot/plugin-magento1#2]
`$sql = "DELETE FROM core_config_data WHERE path LIKE 'trustpilot/trustpilot_general_group/%';";`
should be
`$table = $installer->getTable('core/config_data');`
`$sql = "DELETE FROM {$table} WHERE path LIKE 'trustpilot/trustpilot_general_group/%';";`

Would cause an error on install with custom table prefix

**Comment by knoxjamesus** [comment]
Same issue in Trustpilot_Reviews_Helper_Data::getWebsiteConfigWithSql
```$sql = "SELECT * FROM `core_config_data` WHERE `scope` = 'websites' AND `path` = '" . $path . "' AND `scope_id` = " . self::getWebsiteId();```
should be
```$sql = "SELECT * FROM `{$connection->getTableName('core/config_data')}` WHERE `scope` = 'websites' AND `path` = '" . $path . "' AND `scope_id` = " . self::getWebsiteId();```

Also, using version 2.5.505

**Comment by arunas-stonis** [comment]
Table prefixes were added as you suggested. Thank you!
