### ISSUE TITLE
ajaxUrls broken when store code appended to URLs

### ISSUE THREAD

**Issue by knoxjamesus** [trustpilot/plugin-magento1#3]
ajaxUrl javascript variable is incorrect if store code is appended to URLs in public_html\app\design\adminhtml\default\default\template\trustpilot\system\config\admin.phtml and public_html\app\design\adminhtml\default\default\template\trustpilot\system\config\adminmenu.phtml
```var ajaxUrl = "<?php echo Mage::helper("adminhtml")->getUrl("trustpilot/adminhtml_trustpilot/ajax"); ?>";```
should be
```var ajaxUrl = "<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/trustpilot/ajax"); ?>";```

Using version 2.5.505

**Comment by vilgro** [comment]
Thank you for a comment. We've made a fix
