### ISSUE TITLE
getEmail on possible false shipping address

### ISSUE THREAD

**Issue by knoxjamesus** [trustpilot/plugin-magento1#4]
function tryGetEmail in app\code\community\Trustpilot\Reviews\Helper\OrderData.php assumes getShippingAddress() and getBillingAddress() will return an address object, but in the case of a virtual order, the shipping address is false (as it isn't set)

This change adds truthy value checks to both getShippingAddress() and getBillingAddress()

```
public function tryGetEmail($order) {
...
        else if ($order->getShippingAddress() && !($this->isEmpty($order->getShippingAddress()->getEmail())))
            return $order->getShippingAddress()->getEmail();

        else if ($order->getBillingAddress() && !($this->isEmpty($order->getBillingAddress()->getEmail())))
            return $order->getBillingAddress()->getEmail();
...
```

**Comment by vilgro** [comment]
Thank you, we will change this part.
