### ISSUE TITLE
Close or maintain the repository

### ISSUE THREAD

**Issue by michaelrachlitz** [trustpilot/plugin-magento1#6]
It would be awesome if you would maintain this repository. Alternatively I suggest to close it, so customers gets to install the latest version without confusion.

Thanks

**Comment by vilgro** [comment]
Hey @michaelrachlitz 
This is not the place to get the latest version. This is a place to suggest new **features** or **fix** the bugs. 
But thank you for the comment. We will try to keep it up to date!
